language: r
cache: packages
sudo: false

r:
  - oldrel
  - release
  - devel

r_check_args:
  "--run-donttest --run-dontrun --timings"

before_install:
  - Rscript -e '"pcaL1" %in% rownames(installed.packages()) || install.packages("pcaL1", ask = FALSE)'
  - Rscript -e "update.packages(ask = FALSE)"
  - Rscript -e "if (!'covr' %in% rownames(installed.packages())) install.packages('covr')"
  - Rscript -e "if (!'rgl' %in% rownames(installed.packages())) install.packages('rgl')"
  - Rscript -e "if (!'roxygen2' %in% rownames(installed.packages())) install.packages('roxygen2')"
# Set CXX1X for R-devel, as R-devel does not detect CXX1X support for gcc 4.6.3,
  - if [[ "$TRAVIS_R_VERSION_STRING" = 'devel' ]]; then mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi

before_script:
  - Rscript -e "devtools::document()"

# Only report coverage for the release version
after_success:
- test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
